name: eshop
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  # For http requests
  http: ^1.2.2
  # For state management
  provider: ^6.1.2
  # To create shimmer effect when loading data
  shimmer: ^3.0.0
  # To display lottie progress indicator
  lottie: ^3.1.3
  # For pageviews indicators
  smooth_page_indicator: ^1.2.0+3
  # For cart badge
  badges: ^3.1.2
  # Firebase
  firebase_core: ^3.6.0
  # Firebase database
  cloud_firestore: ^5.4.4
  # Authentification
  google_sign_in: ^6.2.2
  firebase_auth: ^5.3.4
  # Storage with encryption
  flutter_secure_storage: ^9.2.2
  # Display messages in toasts
  fluttertoast: ^8.2.8
  google_fonts: ^6.2.1
  # For credit card payment
  flutter_stripe: ^11.3.0
  country_picker: ^2.0.27
  intl_phone_number_input: ^0.7.4
  flutter_multi_formatter: ^2.13.0
  cached_network_image: ^3.4.1
  flutter_cache_manager: ^3.4.1
  flutter_native_splash: ^2.4.4
  animated_splash_screen: ^1.3.0
  flutter_dotenv: ^5.2.1
  firebase_messaging: ^15.2.2
  flutter_local_notifications: ^18.0.1
  flutter_libphonenumber: ^2.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  change_app_package_name: ^1.5.0

flutter_launcher_icons:
  image_path_android: "assets/images/launcher_icon.png"
  image_path_ios: "assets/images/launcher_icon.png"
  android: "launcher_icon"
  ios: true
  min_sdk_android: 21
  remove_alpha_ios: true
  background_color_ios: "#ffffff"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/launcher_icon.png"

  flutter_lints: ^5.0.0

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/animations/
    - config.env
